/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lars' at '23.10.14 21:41' with Gradle 1.12
 *
 * @author lars, @date 23.10.14 21:41
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
