import static org.junit.Assert.assertTrue;

import org.junit.Test;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'lars' at '23.10.14 21:41' with Gradle 1.12
 *
 * @author lars, @date 23.10.14 21:41
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
